title: Sensoriamento WiFi e rede LPWAN: uma arquitetura fim-a-fim
description: Trabalho de conclusão do curso de Engenharia de Computação na Poli-USP. 
theme: jekyll-theme-cayman

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one